version: 2.1
executors:
  my-executor:
    machine:
     image: ubuntu-1604:202004-01
  my-executor-arm:
    machine:
     image: ubuntu-1604:202004-01
  my-executor-arm64:
    machine:
     image: ubuntu-1604:202004-01
jobs:
  build-image-amd64:
    executor: my-executor
    environment:
      - BUILD_ARCH=amd64
    steps:
      - checkout
      #- run:
      #     name: Check buildx version
      #     command: docker buildx version
      #- run:
      #     name: Create new builder & bootstrap it
      #     command: |
      #            docker buildx create --use --name mybuilder --platform linux/amd64
      #            docker buildx inspect --bootstrap
      #- run:
      #      name: Build image for amd64 based systems
      #      command: cd docker && docker buildx build --platform linux/amd64 -t samip537/lynxchan:latest .
      - run:
           name: Build image for amd64
           command: docker build --build-arg ARCH=amd64 -t samip537/lynxchan -f docker/Dockerfile .
  build-image-arm64:
    executor: my-executor-arm
    environment:
      - BUILD_ARCH=arm32v7
      - BUILD_ARCH=arm64v8
    steps:
      - checkout
     # - run:
     #      name: Check buildx version
     #      command: docker buildx version
     # - run:
     #      name: Create new builder & bootstrap it
     #      command: |
     #             docker buildx create --use --name mybuilder --platform linux/arm64v7,linux/arm64v8
     #             docker buildx inspect --bootstrap
     # - run:
     #       name: Build image for arm64 based systems
     #       command: cd docker && docker buildx build --platform linux/arm64v7,linux/arm64v8 -t samip537/lynxchan:latest .
      - run:
           name: Prepare QEMU
           command: sudo docker run --rm --privileged multiarch/qemu-user-static:amd64-arm64 --reset -p yes
     # - run:
     #      name: Build image for arm64v7, arm64v8
     #      command: cd docker && chmod +x build && ./build
      - run:
           name: Build image for arm32v7
           command: docker build --build-arg ARCH=arm32v7 -t samip537/lynxchan -f docker/Dockerfile.arm32 .
      - run:
           name: Build image for amd64v8
           command: docker build --build-arg ARCH=arm64v8 -t samip537/lynxchan -f docker/Dockerfile.arm64 .
           
workflows:
    build-image-and-deploy-amd64:
      jobs:
        - build-image-amd64
        - build-image-arm64
